<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, RefreshCw } from 'lucide-vue-next'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, errorMessage } from '../lib/api'
import PageHeader from '../components/PageHeader.vue'

const endpoint='/policies/filters'
const loading=ref(false),dialog=ref(false),rules=ref<any[]>([]),testText=ref(''),testResult=ref('')
const form=reactive<any>({id:null,name:'',rule_type:'keyword_exclude',value:'',description:'',priority:10,enabled:true})
async function load(){loading.value=true;try{rules.value=(await api.get(endpoint)).data.data}catch(error){ElMessage.error(errorMessage(error))}finally{loading.value=false}}
function edit(row?:any){const config=row?.config||{};const value=row?.rule_type==='legacy_config'?JSON.stringify(config,null,2):row?.rule_type==='regex'?(config.pattern||''):(config.keywords||config.types||config.senders||config.chat_ids||[]).join('\n');Object.assign(form,row?{...row,value}:{id:null,name:'',rule_type:'keyword_exclude',value:'',description:'',priority:10,enabled:true});dialog.value=true}
function config(){if(form.rule_type==='legacy_config')return JSON.parse(form.value||'{}');if(form.rule_type==='regex')return{pattern:form.value.trim()};const values=form.value.split('\n').map((v:string)=>v.trim()).filter(Boolean);const key=form.rule_type.startsWith('keyword')?'keywords':form.rule_type==='message_type'?'types':form.rule_type==='sender'?'senders':'chat_ids';return{[key]:values}}
async function save(){try{const payload={name:form.name,rule_type:form.rule_type,config:config(),description:form.description,priority:form.priority,enabled:form.enabled};if(form.id)await api.put(`${endpoint}/${form.id}`,payload);else await api.post(endpoint,payload);dialog.value=false;ElMessage.success('过滤规则已保存');await load()}catch(error){ElMessage.error(errorMessage(error))}}
async function remove(row:any){try{await ElMessageBox.confirm('确定删除此过滤规则？','删除确认');await api.delete(`${endpoint}/${row.id}`);await load()}catch(error){if(error!=='cancel')ElMessage.error(errorMessage(error))}}
async function test(){try{const r=await api.post(`${endpoint}/test`,{text:testText.value});testResult.value=r.data.data.should_filter?`已过滤：${r.data.data.reason}`:'允许转发'}catch(error){ElMessage.error(errorMessage(error))}}
onMounted(load)
</script>
<template><PageHeader title="过滤规则" description="按关键字、正则、消息类型、发送者或会话过滤消息"><el-button @click="load"><RefreshCw :size="15"/>刷新</el-button><el-button type="primary" @click="edit()"><Plus :size="15"/>新建规则</el-button></PageHeader><section class="data-panel"><div class="policy-test"><el-input v-model="testText" placeholder="输入测试消息"/><el-button @click="test">测试规则</el-button><span>{{testResult}}</span></div><el-table :data="rules" v-loading="loading"><el-table-column prop="name" label="规则名称"/><el-table-column prop="rule_type" label="类型"/><el-table-column prop="priority" label="优先级" width="90"/><el-table-column prop="description" label="说明"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button size="small" @click="edit(row)">编辑</el-button><el-button size="small" type="danger" plain @click="remove(row)">删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="form.id?'编辑过滤规则':'新建过滤规则'" width="560px"><el-form label-position="top"><el-form-item label="规则名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="规则类型"><el-select v-model="form.rule_type" style="width:100%"><el-option v-for="v in ['keyword_exclude','keyword_include','regex','message_type','sender','chat','legacy_config']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item :label="form.rule_type==='legacy_config'?'配置 JSON':'匹配值（每行一个）'"><el-input v-model="form.value" type="textarea" :rows="5"/></el-form-item><el-form-item label="说明"><el-input v-model="form.description"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="form.priority" :min="0" :max="100"/></el-form-item><el-checkbox v-model="form.enabled">启用规则</el-checkbox></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></template>
