<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, RefreshCw } from 'lucide-vue-next'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, errorMessage } from '../lib/api'
import PageHeader from '../components/PageHeader.vue'

const endpoint='/forwarding/routes'
const loading=ref(false),dialog=ref(false),mappings=ref<any[]>([]),bots=ref<any[]>([])
const form=reactive<any>({id:null,source_chat_id:'',target_bot_ids:[],translation_enabled:true,filter_enabled:true,enabled:true})
async function load(){loading.value=true;try{const[a,b]=await Promise.all([api.get(endpoint),api.get('/connectors/dingtalk/bots')]);mappings.value=a.data.data;bots.value=b.data.data}catch(error){ElMessage.error(errorMessage(error))}finally{loading.value=false}}
function edit(row?:any){Object.assign(form,row?{...row,target_bot_ids:[...row.target_bot_ids]}:{id:null,source_chat_id:'',target_bot_ids:[],translation_enabled:true,filter_enabled:true,enabled:true});dialog.value=true}
async function save(){try{const payload={source_chat_id:Number(form.source_chat_id),target_bot_ids:form.target_bot_ids,translation_enabled:form.translation_enabled,filter_enabled:form.filter_enabled,enabled:form.enabled};if(form.id)await api.put(`${endpoint}/${form.id}`,payload);else await api.post(endpoint,payload);dialog.value=false;ElMessage.success('转发映射已保存');await load()}catch(error){ElMessage.error(errorMessage(error))}}
async function remove(row:any){try{await ElMessageBox.confirm('确定删除此转发映射？','删除确认');await api.delete(`${endpoint}/${row.id}`);await load()}catch(error){if(error!=='cancel')ElMessage.error(errorMessage(error))}}
function botName(id:number){return bots.value.find((bot)=>bot.id===id)?.name||`#${id}`}
onMounted(load)
</script>
<template><PageHeader title="转发映射" description="配置 Telegram 群组或频道到钉钉机器人的转发规则"><el-button @click="load"><RefreshCw :size="15"/>刷新</el-button><el-button type="primary" @click="edit()"><Plus :size="15"/>新增映射</el-button></PageHeader><section class="data-panel"><el-table :data="mappings" v-loading="loading" empty-text="暂无转发映射"><el-table-column prop="source_chat_id" label="来源 Chat ID" min-width="160"/><el-table-column label="目标机器人" min-width="220"><template #default="{row}"><el-tag v-for="id in row.target_bot_ids" :key="id" class="inline-tag">{{botName(id)}}</el-tag></template></el-table-column><el-table-column label="翻译" width="80"><template #default="{row}">{{row.translation_enabled?'开启':'关闭'}}</template></el-table-column><el-table-column label="过滤" width="80"><template #default="{row}">{{row.filter_enabled?'开启':'关闭'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button size="small" @click="edit(row)">编辑</el-button><el-button size="small" type="danger" plain @click="remove(row)">删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="form.id?'编辑转发映射':'新增转发映射'" width="540px"><el-form label-position="top"><el-form-item label="Telegram Chat ID"><el-input v-model="form.source_chat_id" placeholder="例如 -1001234567890"/></el-form-item><el-form-item label="目标机器人"><el-select v-model="form.target_bot_ids" multiple style="width:100%"><el-option v-for="bot in bots" :key="bot.id" :label="bot.name" :value="bot.id"/></el-select></el-form-item><div class="check-row"><el-checkbox v-model="form.translation_enabled">启用翻译</el-checkbox><el-checkbox v-model="form.filter_enabled">启用过滤</el-checkbox><el-checkbox v-model="form.enabled">启用映射</el-checkbox></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></template>
