<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, RefreshCw } from 'lucide-vue-next'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, errorMessage } from '../lib/api'
import PageHeader from '../components/PageHeader.vue'

const endpoint='/policies/templates'
const loading=ref(false),dialog=ref(false),templates=ref<any[]>([]),preview=ref('')
const form=reactive<any>({id:null,name:'',template_text:'[{time}] {sender}: {content}',time_format:'%Y-%m-%d %H:%M',enabled:true,is_default:false})
async function load(){loading.value=true;try{templates.value=(await api.get(endpoint)).data.data}catch(error){ElMessage.error(errorMessage(error))}finally{loading.value=false}}
function edit(row?:any){Object.assign(form,row?{...row}:{id:null,name:'',template_text:'[{time}] {sender}: {content}',time_format:'%Y-%m-%d %H:%M',enabled:true,is_default:false});dialog.value=true}
async function save(){try{const payload={name:form.name,template_text:form.template_text,time_format:form.time_format,enabled:form.enabled,is_default:form.is_default};if(form.id)await api.put(`${endpoint}/${form.id}`,payload);else await api.post(endpoint,payload);dialog.value=false;ElMessage.success('消息模板已保存');await load()}catch(error){ElMessage.error(errorMessage(error))}}
async function action(row:any,type:'preview'|'default'|'delete'){try{if(type==='preview'){preview.value=(await api.post(`${endpoint}/preview`,{template_id:row.id})).data.data.preview}else if(type==='default'){await api.put(`${endpoint}/${row.id}/default`);ElMessage.success('已设为默认模板');await load()}else{await ElMessageBox.confirm('确定删除此消息模板？','删除确认');await api.delete(`${endpoint}/${row.id}`);await load()}}catch(error){if(error!=='cancel')ElMessage.error(errorMessage(error))}}
onMounted(load)
</script>
<template><PageHeader title="消息模板" description="自定义转发消息格式，支持 {time}、{sender}、{content} 等变量"><el-button @click="load"><RefreshCw :size="15"/>刷新</el-button><el-button type="primary" @click="edit()"><Plus :size="15"/>新建模板</el-button></PageHeader><el-alert v-if="preview" :title="preview" type="success" closable style="margin-bottom:14px" @close="preview=''"/><section class="data-panel"><el-table :data="templates" v-loading="loading"><el-table-column prop="name" label="模板名称" min-width="160"/><el-table-column prop="template_text" label="模板内容" min-width="300" show-overflow-tooltip/><el-table-column label="默认" width="90"><template #default="{row}"><el-tag v-if="row.is_default" type="success">默认</el-tag></template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}">{{row.enabled?'启用':'停用'}}</template></el-table-column><el-table-column label="操作" width="310"><template #default="{row}"><el-button size="small" @click="edit(row)">编辑</el-button><el-button size="small" @click="action(row,'preview')">预览</el-button><el-button size="small" @click="action(row,'default')">设为默认</el-button><el-button size="small" type="danger" plain @click="action(row,'delete')">删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="form.id?'编辑消息模板':'新建消息模板'" width="620px"><el-form label-position="top"><el-form-item label="模板名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="模板内容"><el-input v-model="form.template_text" type="textarea" :rows="6"/></el-form-item><el-form-item label="时间格式"><el-input v-model="form.time_format"/></el-form-item><div class="check-row"><el-checkbox v-model="form.enabled">启用</el-checkbox><el-checkbox v-model="form.is_default">设为默认</el-checkbox></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></template>
