<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Plus, RefreshCw } from 'lucide-vue-next'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, errorMessage } from '../lib/api';import PageHeader from '../components/PageHeader.vue'
const tab=ref('filters'),loading=ref(false);const filters=ref<any[]>([]),templates=ref<any[]>([]);const media=reactive<any>({max_file_size_bytes:52428800,allowed_types:['photo','video','document'],thumbnail_enabled:true,thumbnail_max_width:320,thumbnail_quality:75,forward_as_link:false});const translation=reactive<any>({enabled:false,api_key:'',base_url:'https://api.deepseek.com/v1',model:'deepseek-chat'})
const filterDialog=ref(false),templateDialog=ref(false),filterTest=ref(''),filterResult=ref(''),preview=ref('');const filterForm=reactive<any>({id:null,name:'',rule_type:'keyword_exclude',value:'',description:'',priority:10,enabled:true});const templateForm=reactive<any>({id:null,name:'',template_text:'[{time}] {sender}: {content}',time_format:'%Y-%m-%d %H:%M',enabled:true,is_default:false})
async function load(){loading.value=true;try{const[a,b,c,d]=await Promise.all([api.get('/policies/filters'),api.get('/policies/templates'),api.get('/policies/media'),api.get('/policies/translation')]);filters.value=a.data.data;templates.value=b.data.data;Object.assign(media,c.data.data);Object.assign(translation,d.data.data)}catch(e){ElMessage.error(errorMessage(e))}finally{loading.value=false}}
function editFilter(row?:any){const config=row?.config||{};const value=row?.rule_type==='legacy_config'?JSON.stringify(config,null,2):(config.keywords||config.types||config.senders||config.chat_ids||[]).join('\n');Object.assign(filterForm,row?{...row,value}:{id:null,name:'',rule_type:'keyword_exclude',value:'',description:'',priority:10,enabled:true});filterDialog.value=true}
function filterConfig(){if(filterForm.rule_type==='legacy_config')return JSON.parse(filterForm.value||'{}');const values=filterForm.value.split('\n').map((v:string)=>v.trim()).filter(Boolean);if(filterForm.rule_type==='regex')return{pattern:values[0]||''};const key=filterForm.rule_type.startsWith('keyword')?'keywords':filterForm.rule_type==='message_type'?'types':filterForm.rule_type==='sender'?'senders':'chat_ids';return{[key]:values}}
async function saveFilter(){try{const payload={...filterForm,config:filterConfig()};if(filterForm.id)await api.put(`/policies/filters/${filterForm.id}`,payload);else await api.post('/policies/filters',payload);filterDialog.value=false;await load();ElMessage.success('规则已保存')}catch(e){ElMessage.error(errorMessage(e))}}
async function deleteFilter(id:number){try{await ElMessageBox.confirm('确定删除该规则？','删除确认');await api.delete(`/policies/filters/${id}`);await load()}catch(e){if(e!=='cancel')ElMessage.error(errorMessage(e))}}
async function testFilter(){try{const r=await api.post('/policies/filters/test',{text:filterTest.value});filterResult.value=r.data.data.should_filter?`已过滤：${r.data.data.reason}`:'允许转发'}catch(e){ElMessage.error(errorMessage(e))}}
function editTemplate(row?:any){Object.assign(templateForm,row?{...row}:{id:null,name:'',template_text:'[{time}] {sender}: {content}',time_format:'%Y-%m-%d %H:%M',enabled:true,is_default:false});templateDialog.value=true}
async function saveTemplate(){try{if(templateForm.id)await api.put(`/policies/templates/${templateForm.id}`,templateForm);else await api.post('/policies/templates',templateForm);templateDialog.value=false;await load()}catch(e){ElMessage.error(errorMessage(e))}}
async function templateAction(row:any,action:string){try{if(action==='delete'){await ElMessageBox.confirm('确定删除该模板？','删除确认');await api.delete(`/policies/templates/${row.id}`)}else if(action==='default')await api.put(`/policies/templates/${row.id}/default`);else{const r=await api.post('/policies/templates/preview',{template_id:row.id});preview.value=r.data.data.preview}await load()}catch(e){if(e!=='cancel')ElMessage.error(errorMessage(e))}}
async function savePolicy(kind:string){try{await api.put(`/policies/${kind}`,kind==='media'?media:translation);ElMessage.success('配置已保存')}catch(e){ElMessage.error(errorMessage(e))}}
onMounted(load)
</script>
<template><PageHeader title="消息处理" description="集中管理过滤、格式化、媒体和翻译策略"><el-button @click="load"><RefreshCw :size="15"/>刷新</el-button><el-button v-if="tab==='filters'||tab==='templates'" type="primary" @click="tab==='filters'?editFilter():editTemplate()"><Plus :size="15"/>新增</el-button></PageHeader>
<el-tabs v-model="tab" class="section-tabs"><el-tab-pane label="过滤规则" name="filters"/><el-tab-pane label="消息模板" name="templates"/><el-tab-pane label="媒体策略" name="media"/><el-tab-pane label="翻译配置" name="translation"/></el-tabs>
<section v-if="tab==='filters'" class="data-panel"><div class="policy-test"><el-input v-model="filterTest" placeholder="输入测试消息"/><el-button @click="testFilter">测试规则</el-button><span>{{filterResult}}</span></div><el-table :data="filters"><el-table-column prop="name" label="规则"/><el-table-column prop="rule_type" label="类型"/><el-table-column prop="priority" label="优先级" width="90"/><el-table-column prop="description" label="说明"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button size="small" @click="editFilter(row)">编辑</el-button><el-button size="small" type="danger" plain @click="deleteFilter(row.id)">删除</el-button></template></el-table-column></el-table></section>
<section v-else-if="tab==='templates'" class="data-panel"><el-alert v-if="preview" :title="preview" type="success" closable @close="preview=''"/><el-table :data="templates"><el-table-column prop="name" label="模板"/><el-table-column prop="template_text" label="内容" show-overflow-tooltip/><el-table-column label="默认" width="90"><template #default="{row}"><el-tag v-if="row.is_default" type="success">默认</el-tag></template></el-table-column><el-table-column label="操作" width="260"><template #default="{row}"><el-button size="small" @click="editTemplate(row)">编辑</el-button><el-button size="small" @click="templateAction(row,'preview')">预览</el-button><el-button size="small" @click="templateAction(row,'default')">设为默认</el-button><el-button size="small" type="danger" plain @click="templateAction(row,'delete')">删除</el-button></template></el-table-column></el-table></section>
<section v-else-if="tab==='media'" class="form-panel"><el-form label-position="top" class="settings-form"><el-form-item label="最大文件大小 (MB)"><el-input-number :model-value="Math.round(media.max_file_size_bytes/1048576)" :min="1" :max="100" @change="media.max_file_size_bytes=$event*1048576"/></el-form-item><el-form-item label="允许类型"><el-checkbox-group v-model="media.allowed_types"><el-checkbox v-for="v in ['photo','video','document','audio','voice','sticker']" :key="v" :value="v">{{v}}</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="缩略图宽度"><el-input-number v-model="media.thumbnail_max_width" :min="64" :max="4096"/></el-form-item><el-form-item label="缩略图质量"><el-slider v-model="media.thumbnail_quality"/></el-form-item><el-checkbox v-model="media.forward_as_link">媒体统一按链接转发</el-checkbox><div class="form-actions"><el-button type="primary" @click="savePolicy('media')">保存媒体策略</el-button></div></el-form></section>
<section v-else class="form-panel"><el-form label-position="top" class="settings-form"><el-form-item label="状态"><el-switch v-model="translation.enabled"/></el-form-item><el-form-item label="API Key"><el-input v-model="translation.api_key" type="password" show-password/></el-form-item><el-form-item label="API 地址"><el-input v-model="translation.base_url"/></el-form-item><el-form-item label="模型"><el-input v-model="translation.model"/></el-form-item><div class="form-actions"><el-button type="primary" @click="savePolicy('translation')">保存翻译配置</el-button></div></el-form></section>
<el-dialog v-model="filterDialog" :title="filterForm.id?'编辑过滤规则':'新增过滤规则'" width="520px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="filterForm.name"/></el-form-item><el-form-item label="类型"><el-select v-model="filterForm.rule_type" style="width:100%"><el-option v-for="v in ['keyword_exclude','keyword_include','regex','message_type','sender','chat','legacy_config']" :key="v" :label="v" :value="v"/></el-select></el-form-item><el-form-item :label="filterForm.rule_type==='legacy_config'?'配置 JSON':'匹配值（每行一个）'"><el-input v-model="filterForm.value" type="textarea" :rows="4"/></el-form-item><el-form-item label="说明"><el-input v-model="filterForm.description"/></el-form-item><el-form-item label="优先级"><el-input-number v-model="filterForm.priority" :min="0" :max="100"/></el-form-item><el-checkbox v-model="filterForm.enabled">启用</el-checkbox></el-form><template #footer><el-button @click="filterDialog=false">取消</el-button><el-button type="primary" @click="saveFilter">保存</el-button></template></el-dialog>
<el-dialog v-model="templateDialog" :title="templateForm.id?'编辑模板':'新增模板'" width="560px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="templateForm.name"/></el-form-item><el-form-item label="模板内容"><el-input v-model="templateForm.template_text" type="textarea" :rows="6"/></el-form-item><el-form-item label="时间格式"><el-input v-model="templateForm.time_format"/></el-form-item><div class="check-row"><el-checkbox v-model="templateForm.enabled">启用</el-checkbox><el-checkbox v-model="templateForm.is_default">设为默认</el-checkbox></div></el-form><template #footer><el-button @click="templateDialog=false">取消</el-button><el-button type="primary" @click="saveTemplate">保存</el-button></template></el-dialog></template>
