<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { RefreshCw } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import { api, errorMessage } from '../lib/api'
import { limitLabel, planLabel } from '../lib/entitlements'
import PageHeader from '../components/PageHeader.vue'

const loading=ref(false),profile=ref<any>({}),translation=reactive<any>({enabled:false,api_key:'',base_url:'https://api.deepseek.com/v1',model:'deepseek-chat'})
const password=reactive({old_password:'',new_password:'',confirm_password:''})
async function load(){loading.value=true;try{const[p,t]=await Promise.all([api.get('/tenant/profile'),api.get('/policies/translation')]);profile.value=p.data.data;Object.assign(translation,t.data.data)}catch(error){ElMessage.error(errorMessage(error))}finally{loading.value=false}}
async function saveTranslation(){try{await api.put('/policies/translation',translation);ElMessage.success('翻译配置已保存')}catch(error){ElMessage.error(errorMessage(error))}}
async function changePassword(){if(password.new_password!==password.confirm_password)return ElMessage.warning('两次输入的新密码不一致');try{await api.put('/auth/password',{old_password:password.old_password,new_password:password.new_password});Object.assign(password,{old_password:'',new_password:'',confirm_password:''});ElMessage.success('密码已更新')}catch(error){ElMessage.error(errorMessage(error))}}
onMounted(load)
</script>
<template><PageHeader title="系统设置" description="查看租户信息并管理翻译和账号安全"><el-button @click="load"><RefreshCw :size="15"/>刷新</el-button></PageHeader><section class="settings-grid"><div class="data-panel"><div class="panel-title">租户信息</div><el-descriptions :column="2" border><el-descriptions-item label="租户名称">{{profile.name||'-'}}</el-descriptions-item><el-descriptions-item label="当前套餐">{{planLabel(profile)}}</el-descriptions-item><el-descriptions-item label="TG 账号上限">{{limitLabel(profile.tg_account_limit,profile.is_unlimited)}}</el-descriptions-item><el-descriptions-item label="钉钉机器人上限">{{limitLabel(profile.bot_limit,profile.is_unlimited)}}</el-descriptions-item><el-descriptions-item label="转发映射上限">{{limitLabel(profile.mapping_limit,profile.is_unlimited)}}</el-descriptions-item><el-descriptions-item label="成员上限">{{limitLabel(profile.member_limit,profile.is_unlimited)}}</el-descriptions-item></el-descriptions></div><div class="form-panel"><div class="panel-title inset-title">翻译配置</div><el-form label-position="top" class="settings-form"><el-form-item label="启用翻译"><el-switch v-model="translation.enabled"/></el-form-item><el-form-item label="API Key"><el-input v-model="translation.api_key" type="password" show-password/></el-form-item><el-form-item label="API 地址"><el-input v-model="translation.base_url"/></el-form-item><el-form-item label="模型"><el-input v-model="translation.model"/></el-form-item><el-button type="primary" @click="saveTranslation">保存翻译配置</el-button></el-form></div><div class="form-panel"><div class="panel-title inset-title">修改密码</div><el-form label-position="top" class="settings-form"><el-form-item label="原密码"><el-input v-model="password.old_password" type="password" show-password/></el-form-item><el-form-item label="新密码"><el-input v-model="password.new_password" type="password" show-password/></el-form-item><el-form-item label="确认新密码"><el-input v-model="password.confirm_password" type="password" show-password/></el-form-item><el-button type="primary" @click="changePassword">更新密码</el-button></el-form></div></section></template>
